### ISSUE TITLE
How to add custom module

### ISSUE THREAD

**Issue by haolinj** [govCMS/scaffold#18]
Hi, I'm new to GovCMS dev. I'm trying to install a custom module through composer, I can see there is a `custom/composer` folder, so I assume I can add the custom module in the composer.json. The question is how do I get it to load inside in the Drupal after the GovCMS has been started within the docker? I was following the instructions here: https://github.com/govCMS/GovCMS/wiki/1.1-Local-setup

Any help would be appreciated. Thanks.

**Comment by joshua-graham-adelphi** [comment]
For local development only modules (e.g. debugging or migrations) @see https://github.com/govCMS/GovCMS/wiki/An-all-in-one-developer-guide-govCMS-SaaS#adding-development-only-modules

If you wish the custom module to kept on the platform, this is only possible with PaaS (using composer to install etc.)
No custom modules are allowed on the SaaS platform.

**Comment by haolinj** [comment]
Thanks for the info.
